version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=bearblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - MAIN_SITE_HOSTS=${MAIN_SITE_HOSTS}
      - MAIN_DOMAIN=${MAIN_DOMAIN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  nginx:
    ports:
      - "80:80" 